### ISSUE TITLE
Limpar nomes das cidades na coleta

### ISSUE THREAD

**Issue by cuducos** [cuducos/fio-de-ariadne#16]
Hoje a coleta de dados produz um resultado _sujo_ para as cidades (por exemplo, duas cidades com grafia diferentes):

```
Adrianópolis/PR - Bairro Capelinha
Almirante Tamandaré/PR
Araucária / Pr.
Cascavel / Pr.
Colombo / Pr.
Colombo/PR
Corbélia/PR
Curitiba / Pr.
Curitiba/PR
Foz do Iguaçu/PR
Guarapuava/PR - Distrito Guará - Assentamento Rio Banana
Guaratuba / Pr.
Iporã / Pr.
Km 35-BR, João Lunardelli, PR 170 – Sítio São Marcos/PR
Lapa / Pr.
Lidianópolis/PR - Bairro Água da Barra - Sitio São Francisco
Londrina / Pr.
Maringá / Pr.
PARANAGUA/PR
-
```

Precisamor uniformizar isso de alguma forma. Pode ser com  um modelo `City`, ou qualquer outra estratégia. Alguma ideia?

**Comment by glairtonsantos** [comment]
Olá @cuducos eu pensei em utilizar a API do IBGE https://servicodados.ibge.gov.br/api/docs/localidades

Na classe Spider do Estado poderíamos já informar qual serviço para lista os municípios,
ex. `https://servicodados.ibge.gov.br/api/v1/localidades/estados/41/municipios`

e assim utilizar o `re.search` para buscar o município correspondente

**Comment by cuducos** [comment]
Bah… ideia sensacional! A gente bate nessa API, guarda os nomes e depois vai tentando achar com expressão regular (talvez primeiro com cidade e estado e depois só com cidade). Muito bom :purple_heart:
