### ISSUE TITLE
Create a Mother Class for Spiders params

### ISSUE THREAD

**Issue by vmesel** [cuducos/fio-de-ariadne#2]
Hey guys, I saw the website you are scraping, and if you change the URL with another state, it still works and gets the missing child from that state.

I think it would be nice to have a mother class where we just set the `state` in our daughter classes, so the base URL would be universal.

**Comment by cuducos** [comment]
Concordo plenamente, tanto que o spider criado é referente a um estado específico. Apenas deixo um conselho:

> Premature optimization is the root of all evil (or at least most of it) in programming.
> -- Donald Knuth

Em outras palavras, esse _issue_ só é relevante quando tivermos _spiders_ para mais de um estado. Antes disso, ela é irrelevante.

Nessa linha: a prioridade dos estados é PR e SC.

**Comment by cuducos** [comment]
Fechando essa _issue_ para deixar o foco dos raspadores na #18.
Se a resolução dela resultar em muito código repetido, reabrimos essa ; )
