### ISSUE TITLE
Criar chaves da S3 apenas para um "bucket"

### ISSUE THREAD

**Issue by cuducos** [cuducos/fio-de-ariadne#22]
Me deparei com esse problema ao fim da revisão do PR #21. Temos craques na AWS aqui?

**TLDR**, não consigo criar uma conta (IAM) que só permita acesso a um dos meu _buckets_ S3.

---

**Contexto**: na minha conta pessoal, tenho 2 _buckets_, um é [meu site pessoal](https://cuducos.me/) e outro quero usar com nosso projeto aqui, o Fio de Ariadne.

**Problema**: preciso criar chaves de API para o Django do Fio de Ariadne guardar arquivos estáticos e de mídia. Mas, como tem mais gente nesse projeto com acesso ao ambiente de produção, não gostaria que essas pessoas pudessem (acidentalmente ou não) mexer no S3 do meu site pessoal.

**O que eu tentei**

Pelo o que entendi na AWS, o caminho seria criar uma _política_, atribuir essa política a um _grupo_ e depois criar um _usuário_ nesse grupo – tudo pelo IAM. Fiz tudo isso, mas não funcionou. Quando o Django tenta subir arquivos, dá erro dizendo que essa chave de API não tem permissão para criar objetos no S3:

```
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
```

Minha política de acesso ficou assim:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowUserToReadWriteObjectData",
            "Action": [
                "s3:PutObject"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::fio-de-ariadne/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::fio-de-ariadne"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::fio-de-ariadne/*"
            ]
        }
    ]
}
```

Tentei também sem esse primeiro bloco (`AllowUserToReadWriteObjectData`) e não rolou. Em ambos os casos, na [simulação de políticas da AWS](https://policysim.aws.amazon.com/home/index.jsp?#groups)  aparece o mesmo erro, _Implicitly denied (no matcing statements)_, com a descrição (que não ajuda muito, pois diz, basicamente, que esse teste seria a excessão):

> This action belongs to a service that supports special access control mechanisms in addition to resource-based policies, such as S3 ACLs or Glacier vault lock policies. The policy simulator does not support these mechanisms, so the results can differ from your production environment.

Alguma dica?

Muito obriagdo,

**Comment by decko** [comment]
No bucket q eu tenho o Sid está como `AddPerm`. Depois, em Access Control List deva rolar vc adicionar o seu grupo "especial" para acessos.

**Comment by ericovis** [comment]
Eu sugiro vc criar um usuário sem permissões nenhuma, só pra gerar uma access key. E depois criar uma bucket policy (não é IAM policy) no bucket que vc deseja para liberar as permissões necessárias. 

Criar um grupo no IAM pro usuário e gerenciar as permissões por lá é overkill se vc só precisa dar acesso ao bucket X e se vc não pretende replicar esse comportamento pra outros usuários.

O teu bucket policy seria algo do tipo: 

```json
{
  "Version":"2012-10-17",
  "Statement":[
    {
      "Sid":"AllowSingleUser",
      "Effect":"Allow",
      "Principal": {"AWS": ["arn:aws:iam::<account_number>:<iam_user>"]},
      "Action":["s3:*"],
      "Resource":["arn:aws:s3:::<bucket_name>/*", "arn:aws:s3:::<bucket_name>"]
    }
  ]
}
```

Se liga q ali to dando (Effect: Allow) full permissions (Action) pro usuário (Principal) no bucket e objetos q ele contém (Resource)

Eu to desempregado e entediado, qualquer coisa da um ping q eu te ajudo na config 🤣

**Comment by cuducos** [comment]
@decko, no ACL no _bucket_ não achei opção de adicionar um grupo ou identidade (IAM), apenas a conta toda.

@ericovis, o bucket está público para leitura, joguei (pelo navegador) um arquivo aleatório lá só para testar: https://fio-de-ariadne.s3-sa-east-1.amazonaws.com/True+Story.pdf

O _Block public access_ (do _bucket_) está:


> * Block public access to buckets and objects granted through new access control lists (ACLs)<br>**On**
> * Block public access to buckets and objects granted through any access control lists (ACLs)<br>**On**
> * Block public access to buckets and objects granted through new public bucket or access point policies<br>**Off**
> * Block public and cross-account access to buckets and objects through any public bucket or access point policies<br>**Off**

E as políticas do grupo:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PublicRead",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::fio-de-ariadne/*"
        }
    ]
}
```

Eu tentei itilizar apenas a política do _bucket_ como o Eric indicou (e removi as do usuário que criei) e também não funcionou : (

**Comment by thiagoalmeidasa** [comment]
Eu uso essa role policy pra isso. Vê se funciona pro teu caso.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "s3:ListAllMyBuckets",
                "s3:GetBucketLocation"
            ],
            "Resource": "arn:aws:s3:::*"
        },
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::fio-de-ariadne/*",
                "arn:aws:s3:::fio-de-ariadne/",
                "arn:aws:s3:::fio-de-ariadne"
            ]
        }
    ]
}

```

**Comment by cuducos** [comment]
Resolvido. O [Django Storages](https://django-storages.readthedocs.io/) aparentemente precisa da permissão `PutObjectVersionAcl` e `PutObjectAcl`.

Utilizei essa política no _bucket_, e um usuário sem grupo ou política, como o @ericovis sugeriu!

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PublicRead",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::fio-de-ariadne/*"
        },
        {
            "Sid": "DjangoStorages",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::XXXXXXXXXXXX:user/fio-de-ariadne"
            },
            "Action": [
                "s3:PutObject",
                "s3:GetObjectAcl",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:DeleteObject",
                "s3:PutObjectAcl",
                "s3:PutObjectVersionAcl"
            ],
            "Resource": [
                "arn:aws:s3:::fio-de-ariadne/*",
                "arn:aws:s3:::fio-de-ariadne"
            ]
        }
    ]
}
```

**Comment by ericovis** [comment]
Estranho que colocando s3:* em actions em teoria era pra dar todas as permissões naquele bucket. de qualquer forma que bom q deu certo
