### ISSUE TITLE
Qual o usuário / senha padrão para cessar o web app?

### ISSUE THREAD

**Issue by hsteinshiromoto** [cuducos/fio-de-ariadne#28]
Caros,

Consigo rodar o web app mas não estou conseguindo fazer login. Qual seria o usuário e senha padrão para entrar no webapp a partir da tela de login (ver imagem abaixo)?

![image](https://user-images.githubusercontent.com/4290588/109416829-a1f42a00-7a14-11eb-8dbb-c4f2a62af6b9.png)

Ps.: Estou rodando as imagens do Docker.

**Comment by cuducos** [comment]
Não sei. O usuário e senha são criados por você, então só você sabe. Seguindo as instruções do`README.md` tem um comando chamado `createsuperuser` — a resposta para a tua pergunta é o usuário e senha que vc criou com esse comando.
