### ISSUE TITLE
Adicionar campo explícito com foto(s) da criança 

### ISSUE THREAD

**Issue by cuducos** [cuducos/fio-de-ariadne#6]
No modelo de dados, filtros e visualizações do Admin, mostrar a foto(s) da criança desaparecida. Provavelmente temos que usar algum _storage_ para isso. Qualquer coisa que integre legal com o `django-storages` acho que fica simples de implementar!

**Comment by gu-stat** [comment]
Pergunta de alguem que descobriu Django ha 20 minutos: qual a vantagem de usar django-storages no lugar de um RDBMS usando PostgreSQL?

**Comment by cuducos** [comment]
Resposta de quem não conhece RDBMS: nem ideia hahaha…

Quer falar mais da tua proposta?

**Comment by cuducos** [comment]
Ok, fiz minha pesquisa e parece que a sigla é só um jeito técnico de dizer banco de dados relacional! Yay, aprendi algo novo hoje já!

Sendo assim, a vantagem de usar um storage seria basicamente: storage é muito mais barato que banco de dados (preço de contratação de serviços) e storage é mais eficiente para servir arquivos, o que resulta e outras vantagens: menor tempo de resposta para o usuário, menos carga de processamento nos permite ter um servidor mais barato para o Django.

**Comment by gu-stat** [comment]
Entendi. Vou aprender mais sobre o Django para poder dar sugestoes. 

Uma coisa que eu fiz ano passado foi montar uma base no PostgreSQL a partir de um crawler e criei um indice chave para cada observacao. Usei esse mesmo indice para nomear as images e salva-las num servidor. Na base, inclui um link para as imagens, entao era de facil acesso.

No seu caso, poderia ser uma string com os seguintes campos concatenados: as primeiras letras do nome, data desaparecimento, UF, indice de entrada na base. Um exemplo, usando os dados do Parana, o primeiro caso seria: EVF10111994PR1. No caso das imagens (cada caso pode ter mais de uma), os indices seriam EVF10111994PR1_IMG1. 

Com algo assim, ficaria facil fazer a ligacao das informacoes do banco com as imagens. E se montar um outro banco soh com os Historicos, podemos relacionar as bases tambem.

Outro ponto positivo eh que esse tipo de formato da chave (nome, data, uf, indice) facililta se algum dia alguem precisar fazer alguma manipulacao com expressoes regulares, e iteracoes pela UF e indice dos casos .

**Comment by juniorcarvalho** [comment]
vamos escolher qual storage ?
https://django-storages.readthedocs.io/en/latest/
Dropbox seria uma boa inicialmente pelo fato da conta gratuita.

**Comment by cuducos** [comment]
@gu-stat, mas isso pode ser feito no _storage_ também, sem problemas. E fica **muito** mais barato. Exemplo: no DigitalOcean Spaces por 5 dólares por mês voce leva 250 GB de armazenamento e 1 TB de tráfego; no Heroku, 256GB de espaço no Postgres custa 200 dólares — 40x mais. E isso sem contar que vai aumentar a carga de trabalho do Django e teríamos que investir mais na máquina que roda o Django.

Sobre baixar os dados, teremos (além da possibilidade de padronizar os nomes), uma API aberta para isso!

**Comment by cuducos** [comment]
@juniorcarvalho, Dropbox nas minhas provas de conceito era leve para esse fim. Prefiro usar um S3 que é virtualmente de graça. Meu blog fica lá (gerador de arquivos estáticos); mês passado teve 16 milhões de requisições e ficou 1 dólar, valor que a Amazon não se dá ao trabalho de cobrar (acho que cobram quando é mais de 5 dólares só). Mas se for implementar, pode escolher e qualquer coisa eu ajusto no deploy aqui ; )

**Comment by gu-stat** [comment]
@cuducos Entendi. Bom saber isso dos valores de armazenamento. Valeu.
E, como falei, preciso aprender mais sobre o Django e sobre como as coisas funcionam na API antes de dar sugestoes. 
Na superficie, o objetivo parece ser o mesmo do pacote Shiny do R, mas tem algumas coisas internas bem diferentes (tb por conta das diferencas entre o R e o Python).

**Comment by juniorcarvalho** [comment]
@cuducos como vc disse 'as fotos' então uma criança pode ter mais de uma foto, 
vou criar uma model KidImage onde teremos a relação para kid e o campo image. Dai na listagem da model incluimos uma coluna mostrando a primeira foto. E registramos a model KidImage no admin.O que acha ?

**Comment by cuducos** [comment]
Excelente! Vi o PR #21, é um bom caminho : )

**Comment by juniorcarvalho** [comment]
@cuducos joia! ja está finalizado. Fiz uns testes local aqui e esta funcionando OK, gravando no s3.
Outro detalhe, não quer abrir uma issue para escrevermos uns testes na app web ?
